# Base defaults for NV Speech Player frontend.
#
# Packs are merged in this order:
#   default.yaml -> <lang>.yaml -> <lang-region>.yaml -> <lang-region-variant>.yaml

settings:
  # Timing / stress shaping
  primaryStressDiv: 1.5
  secondaryStressDiv: 1.2

  # Stop closure insertion ("click" before stops/affricates)
  stopClosureMode: vowel-and-cluster
  stopClosureClusterGapsEnabled: true
  stopClosureClusterGapMs: 22
  segmentBoundaryGapMs: 12
  segmentBoundaryFadeMs: 6
  # Default is true even if you omit it.
  # Set false only if you explicitly want pauses even between vowel→vowel.
  segmentBoundarySkipVowelToVowel: true
  # If a language relies on lots of vowel-hiatus without explicit syllable boundaries, keep these off (or only enable autoTieDiphthongs and leave the semivowel conversion off).
  autoTieDiphthongs: false
  autoDiphthongOffglideToSemivowel: true  
  # Length mark (ː) handling
  lengthenedScale: 1.05
  lengthenedScaleHu: 1.4
  applyLengthenedScaleToVowelsOnly: true

  # Output gain defaults
  defaultPreFormantGain: 2.0
  defaultOutputGain: 1.5

# Global intonation defaults.
# These override the frontend's built-in eSpeak-like tables.
#
# Goal here: less "always falling" speech, fewer bouncy pitch steps,
# and more predictable contours at high rates.
#
# Values are pitch percents (0..100) used by the frontend's pitchFromPercent().
  legacyPitchMode: false
  legacyPitchInflectionScale: 0.58

  # Normalization cleanup
  stripAllophoneDigits: true
  stripHyphen: true

  # Tonal languages
  tonal: false
  toneDigitsEnabled: true
  toneContoursMode: absolute

# Global IPA normalizations that are *not* language-specific.
# These closely match the multi-character replacements in ipa_bestversion.py.
  stressedVowelHiatusGapMs: 0
  stressedVowelHiatusFadeMs: 0
  semivowelOffglideScale: 1.0
normalization:
  preReplacements:
    # Strip eSpeak joiners / format chars so tokens match (e.g. ə‍l, e‍ɪ, etc.)
    # We include BOTH the escaped form (\uXXXX) and the literal char, since some parsers don't unescape.
    - from: "\u200d"   # ZWJ
      to: ""
    - from: "‍"       # ZWJ literal
      to: ""

    - from: "\u200c"   # ZWNJ
      to: ""
    - from: "‌"       # ZWNJ literal
      to: ""

    - from: "\u200b"   # ZWSP
      to: ""
    - from: "​"       # ZWSP literal
      to: ""

    - from: "\u2060"   # WORD JOINER
      to: ""
    - from: "⁠"       # WORD JOINER literal
      to: ""

    # Rare, but shows up in some IPA sources:
    - from: "\u034f"   # CGJ
      to: ""
    - from: "͏"       # CGJ literal
      to: ""

    # Some environments still leak BOM/ZWNBSP into strings:
    - from: "\ufeff"   # BOM / ZWNBSP
      to: ""
    - from: "﻿"       # BOM / ZWNBSP literal
      to: ""

    # Tie common affricate spellings into the single phonemes in Phonemes.yaml.
    - from: "tʃ"
      to: "t͡ʃ"
    - from: "dʒ"
      to: "d͡ʒ"
    - from: "tɕ"
      to: "t͡ɕ"
    - from: "dʑ"
      to: "d͡ʑ"
    - from: "ts"
      to: "t͡s"
    - from: "dz"
      to: "d͡z"

    # eSpeak mnemonic variants (harmless if you only feed true IPA).
    - from: "tS"
      to: "t͡ʃ"
    - from: "dZ"
      to: "d͡ʒ"
    - from: "t͡S"
      to: "t͡ʃ"
    - from: "d͡Z"
      to: "d͡ʒ"

    # eSpeak sometimes inserts zero-width joiners in IPA output (e.g. ɑː‍ɹ).
    # Strip them so string-based normalization rules match reliably.
    - from: "\u200d"
      to: ""
    - from: "\u200c"
      to: ""
    - from: "\u200b"
      to: ""
    - from: "\u2060"
      to: ""
